name: Build, Test, and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - action
    paths:
      - 'Dockerfile'
      - 'test/fips_test'
env:
  docker_user: ${{ vars.DOCKER_HUB_USERNAME}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.docker_user }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: |
            ${{ env.docker_user }}/alpine-fips:latest
            ${{ env.docker_user }}/alpine-fips:3.19
    - name: Run tests
      run: |
        ls
        pwd
        docker run --rm ${{ env.docker_user }}/alpine-fips:latest openssl list -providers
        docker run -itd -v ./test:/test --name=alpine_test ${{ env.docker_user }}/alpine-fips:latest sh
        docker exec alpine_test ls -lh /test 
        docker exec alpine_test chmod a+x /test/fips_test
        docker exec alpine_test ls -lh /test 
        docker exec alpine_test /test/fips_test
        docker rm -f alpine_test
        

    - name: Push to Docker Hub
      if: success() 
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
            ${{ env.docker_user }}/alpine-fips:latest
            ${{ env.docker_user }}/alpine-fips:3.19
