name: Build, Test, and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - action
    paths:
      - 'Dockerfile'
      - 'test/fips_test'


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: 
            shuimqcn/alpine-fips:latest
            shuimqcn/alpine-fips:3.19
    - name: Run tests
      run: |
        docker run --rm shuimqcn/alpine-fips:latest openssl list -providers
        docker run --rm -v test:/test shuimqcn/alpine-fips:latest chmod a+x /test/* && /test/fips_test
        

    - name: Push to Docker Hub
      if: success() 
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: 
            shuimqcn/alpine-fips:latest
            shuimqcn/alpine-fips:3.19
